2FOC pwm feedback 5 bits shift bugfix
robotology/icub-firmware pull request #177
Opened 2021-03-25 16:26 UTC by ale-git

This PR fixes the 2FOC pwm feedback bug, that caused a 32x factor in the pwm feedback sent by the 2FOC to the EMS board, related to issue https://github.com/icub-tech-iit/task-force-miscellanea/issues/69

2021-03-25 16:32 UTC, pattacini reviewed
@ale-git this PR contains stuff that seems to be quite unrelated to the problem: for example the code under `#ifdef FINGER_MK3` or many project files.

To fix this, you may consider push-forcing on your fork.

cc @S-Dafarra

2021-03-25 16:36 UTC, pattacini commented
@ale-git it's also crucial to clarify the following points from the discussion we're having in the related issue:
>- Does this mean that the PIDs were indeed affected?
>- Do the PID gains need to be changed after this fix to maintain the existing behavior? In that case, this could involve a non-trivial robots-configuration migration
- How does this change affect all the iCub robots?

2021-03-25 20:39 UTC, pattacini requested changes
Please clean up the PR.

2021-03-30 11:24 UTC, pattacini commented on emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/include/2FOC.h
> +volatile extern char IKs;
@ale-git can you clarify what `IKs` is for?

2021-03-30 15:04 UTC, ale-git commented on emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/include/2FOC.h
> +volatile extern char IKs;
Hi @pattacini , IKs is a shift factor since the calculations are performed in fixed point. 
About the PIDs the answer is no, they aren't affected. Only the pwm feedback sent to the EMS, that is never used in control but only for logging purposes, is affected. No action is required to maintatin the former behaviour, now we simply have the right pwm feedback value.

2021-03-30 15:08 UTC, pattacini commented on emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/include/2FOC.h
> +volatile extern char IKs;
Thanks @ale-git 👍🏻 
We need only to clean up the PR then 🧹

2021-03-30 16:14 UTC, marcoaccame requested changes
Hi @ale-git , the commit w/ the `FINGER_MK3` comes from this [PR](https://github.com/robotology/icub-firmware/pull/173) which is already merged. So, yes: the commit must be removed (I believe it is the same issue addressed by @pattacini).

All the rest seems fine. 

Also, pls remember to build new binaries for the 2foc board (in icub-firmware-build I can see also the ones for R1) and prepare the associated PR.

2021-04-06 20:20 UTC, pattacini commented
Hi @ale-git we'd need to accelerate the pace on this in order to complete the process.
As said above, we need to:
- clean up the PR in order to retain only what's really relevant to it (you can do that by force-pushing new commits on the compare branch)
- yield the new binaries

2021-04-09 08:21 UTC, pattacini approved these changes

2021-04-09 08:22 UTC, pattacini commented
It's all good now from my side.
@marcoaccame could you review it again?

2021-04-12 09:36 UTC, marcoaccame approved these changes

2021-04-12 09:37 UTC, marcoaccame approved these changes
OK

2021-04-12 09:38 UTC, merged

2021-04-12 09:38 UTC, pattacini commented
@ale-git we'd need now to upload the new binaries.

2021-04-12 09:38 UTC, marcoaccame commented
Hi @ale-git:

> Also, pls remember to build new binaries for the 2foc board (in icub-firmware-build I can see also the ones for R1) and prepare the associated PR.

2021-05-04 12:40 UTC, ale-git commented
I've generated the binaries:

https://github.com/robotology/icub-firmware-build/pull/28