Strain2: added axis remapping to stream data with the same reference …
robotology/icub-firmware pull request #182
Opened 2021-04-26 14:25 UTC by simeonedussoni

…frame for the IMU and FT

modified strain project to have the following axis exchange in the IMU data
- $ x \arrowto y$
- $ y \arrowto -x$
- $ z \arrowto z $

In this way the FT and the IMU have the same reference frame. 

The code is modified with a conditional preprocessing to insure the compatibility b/w the strain and the other boards equipped with the BNO055, that don't need to have the axis remapped.

2021-04-26 14:54 UTC, pattacini requested changes
Thanks @simeonedussoni 

Can you please clean up the PR in order to remove changes to the project files?

Also, please be neat next time w/ the title of the PR 😏

2021-04-26 15:14 UTC, traversaro commented
Not critical, but it would be also great to avoid mixing space and tabs, as these results in rendering issues (`#if` and `#else` should be aligned):
![tabsandsapces](https://user-images.githubusercontent.com/1857049/116106946-dc93df00-a6b2-11eb-924d-6ff1f3bbbe13.PNG)

2021-04-27 06:49 UTC, pattacini commented
Good point @traversaro 👍🏻 

>Can you please clean up the PR in order to remove changes to the project files?

Of course, I meant referring only to those files that do not need to be changed as I guess that the `define` has to be saved somewhere in the project.

2021-04-27 07:00 UTC, marcoaccame commented
> Not critical, but it would be also great to avoid mixing space and tabs, as these results in rendering issues (#if and #else should be aligned):

yes, I opened the PR this morning because yesterday I spotted that and I wanted address this point.
To avoid presence of tabs it is wise to configure the text editor to substitute the tab w/ 4 spaces.
All (most of) the code in `icub-firmware` and `icub-firmware-shared` is edited w/out tabs because they give a different alignment which depends on the configuration of the editor.

> Can you please clean up the PR in order to remove changes to the project files?

If the project does not change an option such as optimization, include path or similar, we don't need / want to commit its changes.

2021-04-27 07:29 UTC, marcoaccame requested changes
Hi @simeonedussoni,

some issue have already been addressed but here they are anyway:
- [ ] no need to commit the project files;
- [ ] change of tabs w/ 4 characters so that the code stays aligned as the style of the existing code;


For the rest, it seems to me that everything is fine. 

I assume that the the rotation is correct and no tests are required.

A comment on the use of macro `STM32HAL_BOARD_STRAIN2`.

The macro `STM32HAL_BOARD_STRAIN2` must be (and is) defined in all the projects running on the strain2 boards. It is designed to offer specialized behaviour to one board and not others. There are similar macros for other boards such as `STM32HAL_BOARD_RFE` etc.

The change you did to file `embot_app_application_theIMU.cpp` must be conditioned under this macro `STM32HAL_BOARD_STRAIN2` because (if) we want to rotate the IMU values only for the `strain2` board but not for the `mtb4` and `rfe` boards which are the other boards using this code.

That is important because the IMU values streamed from the `rfe` are used as they are now for getting the orientation of the head and any change in these values may lead to problems in high level code.

2021-04-27 08:54 UTC, simeonedussoni commented
changes requested are implemented.

2021-04-27 09:11 UTC, pattacini requested changes
I don't see where the macro `STM32HAL_BOARD_STRAIN2` is defined.
Perhaps in the FT FW project?

My point was to remove changes to those project files that are unrelated but to retain those relevant.

2021-04-27 09:19 UTC, simeonedussoni commented
it's defined in the strain2-application-v6 project file, in a tab dedicated to preprocessor macros.

2021-04-27 09:20 UTC, simeonedussoni commented
> The macro `STM32HAL_BOARD_STRAIN2` must be (and is) defined in all the projects running on the strain2 boards. It is designed to offer specialized behaviour to one board and not others. There are similar macros for other boards such as `STM32HAL_BOARD_RFE` etc.

as is stated from @marcoaccame here

2021-04-27 09:23 UTC, pattacini commented
This file doesn't seem to be contained in this PR though.
So, how could one download the `icub-firmware` repo anew and build the project for the FT FW from scratch?

Am I missing a step?

2021-04-27 09:39 UTC, simeonedussoni commented
> 
> 
> This file doesn't seem to be contained in this PR though.
> So, how could one download the `icub-firmware` repo anew and build the project for the FT FW from scratch?
> 
> Am I missing a step?

BTW this is the PR for the IMU remap, after f2f briefing with @marcoaccame we decided to keep the two PR separated. 
In the default project file there is defined among others the preprocessor macro quoted by marco. 
Thus one just needs to download the repo `icub-firmware`, its sibling `icub-firmware-shared` and build the project to obtain a local copy of the executable file. 

As stated above by marco, the project file (which is unchanged from the original one) `strain2-application-v6.uvproj` is not been included in the PR (actually it is just updated by the Keil toolchain when opened with some local environment options which do not impact the binary file generation)

2021-04-27 09:42 UTC, pattacini commented
>As stated above by marco, the project file (which is unchanged from the original one) strain2-application-v6.uvproj is not been included in the PR 

So, you're saying that the macro was already defined in the project file? If so, we're ok 👍🏻 
It wasn't clear from the posts above.

2021-04-27 09:43 UTC, pattacini approved these changes

2021-04-27 10:06 UTC, merged

2021-04-27 10:06 UTC, pattacini commented
Merged ✔
@simeonedussoni could you yield the binaries now?