Can battery devel
robotology/icub-firmware pull request #285
Opened 2022-07-25 12:20 UTC by triccyx

Added the support for the battey via CAN

2022-07-25 12:56 UTC, pattacini commented
Hi @triccyx 

The version of the FW should be 1.26.0 as well.
Ref: https://github.com/robotology/icub-firmware-shared/pull/63.

2022-07-25 13:00 UTC, marcoaccame requested changes
Hi @triccyx I have finished editing the review.

I have written some comments alongside the code.

In addition to that:
- you need to update the projects also of the `mc4plus` and `mc2plus` to have the new `theBATservice`. Otherwise I suspect that they will not compile anymore. 
- and also don't forget to update: date + application versions for `ems`, `mc4plus` and `mc2plus`.

2022-07-25 13:00 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/embobj/plus/can/EOtheCANmapping.c
> +        {10,  0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf , 0xf}    // ep->sk [sk, none]
In the line of ep->sk we need to change 10 w/ 11 otherwise skin service does not work anymore

2022-07-25 13:00 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/libs/highlevel/abslayer/ipal/ipal.uvopt
> +    <tExt>*.txt; *.h; *.inc; *.md</tExt>
the ipal project files (uvopt, etc.)  don't need to be modified, so better reverting them.

2022-07-25 13:03 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/cfg/eoemsappl/overridden_appl.c
> +    // bat service
similar lines should be added also to the relevant files (`overridden_appl.c` and `overridden_runner.c`) of boards `mc4plus` and `mc2plus`.

2022-07-25 13:08 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/embot_app_eth_theBATservice.h
> +class theBATService {
the file `embot_app_eth_theFTservice.h` which we used as a template to obtain `theBATservice` has a different tab indentation w/ 4 spaces.

2022-07-25 13:09 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/embot_app_eth_theFTservice.h
> -
this file does not need changes, better to revert them

2022-07-25 13:13 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/embot_app_eth_theBATservice.h
> +class theBATService {
for class name is better using `theBATservice` (as from `theFTservice`).

2022-07-25 13:25 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/embot_app_eth_theBATservice.cpp
> +         eoas_bms_isboardvalid(static_cast<eObrd_cantype_t>(
see https://github.com/robotology/icub-firmware-shared/pull/63#discussion_r928881032

2022-07-25 13:40 UTC, marcoaccame requested changes

2022-07-25 13:40 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/embot_app_eth_theBATservice.cpp
> +// finally the implementation struct
the file `embot_app_eth_theFTservice.cpp` which we used as a template to obtain `theBATservice` has a different tab indentation w/ 4 spaces.

2022-07-27 10:38 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/embobj/plus/can/EOtheCANmapping.c
> +        {10,  0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf , 0xf}    // ep->sk [sk, none]
Not OK. 

The line of ep->sk is line 783.

The code must be:

```C++
    static const uint8_t pos[s0][s1] = // pos[eoprot_endpoints_numberof][eoprot_entities_maxnumberofsupported] = 
    {
        {0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf , 0xf},   // ep->management [none, ...]
        {0,     1, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf , 0xf},   // ep->mc [joi, mot, none, ...]
        {2,     3,   4,   5,   6,   7,   8,   9 , 10},   // ep->as [str, mai, tem, ine, ine3, psc, pos, ft, bat]
        {11,  0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf , 0xf}    // ep->sk [sk, none]
    }; EO_VERIFYsizeof(pos, sizeof(const uint8_t)*(eoprot_endpoints_numberof)*(eoprot_entities_maxnumberofsupported))
```

2022-07-27 10:48 UTC, marcoaccame commented
> * you need to update the projects also of the `mc4plus` and `mc2plus` to have the new `theBATservice`. Otherwise I suspect that they will not compile anymore.
> * and also don't forget to update: date + application versions for `ems`, `mc4plus` and `mc2plus`.

I have just tested compilation of the ETH boards and here is the list of which projects do not compile because they need inclusion of the new files for the battery:  `ems4rd.wristmk2.uvprojx`, `mc4plus.diagnostic2ready.uvprojx`, `mc4plus.handv3.uvprojx`, `mc2plus.diagnostic2ready.uvprojx`.

And also, you need to update the the version and release date of the ETH boards.

In here is the case for the `ems`

```diff
//  <h> version
//  <o> major           <0-255> 
#define EOMTHEEMSAPPLCFG_VERSION_MAJOR          (VERSION_MAJOR_OFFSET+3)
//  <o> minor           <0-255> 
//  <o> minor           <0-255>
-#define EOMTHEEMSAPPLCFG_VERSION_MINOR          52
+#define EOMTHEEMSAPPLCFG_VERSION_MINOR          53

//  </h>version

//  <h> build date
//  <o> year            <2010-2030>
#define EOMTHEEMSAPPLCFG_BUILDDATE_YEAR         2022
//  <o> month           <1-12>
-#define EOMTHEEMSAPPLCFG_BUILDDATE_MONTH        6
+#define EOMTHEEMSAPPLCFG_BUILDDATE_MONTH        7
//  <o> day             <1-31>
-#define EOMTHEEMSAPPLCFG_BUILDDATE_DAY          21
+#define EOMTHEEMSAPPLCFG_BUILDDATE_DAY          27
//  <o> hour            <0-23>
-#define EOMTHEEMSAPPLCFG_BUILDDATE_HOUR         14
+#define EOMTHEEMSAPPLCFG_BUILDDATE_HOUR         12
//  <o> minute          <0-59>
-#define EOMTHEEMSAPPLCFG_BUILDDATE_MIN          40
+#define EOMTHEEMSAPPLCFG_BUILDDATE_MIN          47
//  </h>build date
// </h>Info 

```

2022-07-28 08:02 UTC, marcoaccame commented
> But I have this error:
../../../../../../../../../icub-firmware-shared/embot/core\embot_core.h(14): error: 'cstdint' file not found

ems4rd.wristmk2.uvprojx + mc4plus.diagnostic2ready.uvprojx + mc2plus.diagnostic2ready.uvprojx
must compile `EoCANprotBSperiodic.c` as a C++ file and it solve the above

> and in one project also this:
../../../../../embobj/plus/mc/Joint_hid.h(4): error: 'kalman_filter.h' file not found

whcih one?

2022-07-29 07:34 UTC, marcoaccame approved these changes
Hi @triccyx: that is fine

2022-07-29 12:03 UTC, merged