Improved calib type 6 w/ FAP.
robotology/icub-firmware pull request #349
Opened 2023-02-28 13:09 UTC by MSECode

Tested and working on both desk setup and ergocab robot.

In this PR the following tasks have been done:
- Improve current working calibration type 6 by allowing to use FAP sensors instead of MICE;
- Tested the calibration procedure on the left arm bench setup.
- Tested the calibration procedure on the left arm of ergocub robot (test on right arm is going to be done)
- Updated firmware code by customizing calibration type 6 enabling POS service use

2023-03-02 08:09 UTC, marcoaccame commented
Hi @MSECode, welcome to your first PR in robotology/icub-firmware. I will have a look at it later today.

2023-03-02 15:18 UTC, marcoaccame requested changes
The PR is fine. I assume it was tested on the robot. 
I have just noted the `snprintf` but they are very minor things. 

Thanks for your contribution.

2023-03-02 15:18 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +                sprintf(info,"calib 6:outLim: cp:%d mx:%.1f mn:%.1f",curr_pos, j_ptr->pos_max, j_ptr->pos_min);
just an improvement: `snprintf(info, sizeof(info), `

2023-03-02 15:18 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +                sprintf(info,"m_min=%d m_max=%d", m_ptr->pos_min, m_ptr->pos_max );
just an improvement: `snprintf(info, sizeof(info), `

2023-03-02 15:18 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +            sprintf(info,"calib Completed" );
just an improvement: `snprintf(info, sizeof(info), `

2023-03-02 15:18 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/embobj/plus/mc/JointSet.c
> +            snprintf(info, 50, "vmax=%d,vim=%d",calibrator->params.type6.vmax, calibrator->params.type6.vmin);
just an improvement: `snprintf(info, sizeof(info), `

2023-03-02 15:20 UTC, marcoaccame commented
Companion PR is: 
- https://github.com/robotology/icub-firmware-build/pull/71

2023-03-02 17:06 UTC, MSECode commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +                sprintf(info,"calib 6:outLim: cp:%d mx:%.1f mn:%.1f",curr_pos, j_ptr->pos_max, j_ptr->pos_min);
Oks, I'll fix that and I'll submit the change

2023-03-03 09:14 UTC, MSECode commented
Submitted changes in [commit ](https://github.com/valegagge/icub-firmware/commit/e3df97a6598d1859cc780e358349f3542a761d46)

2023-03-03 13:19 UTC, marcoaccame approved these changes

2023-03-03 13:19 UTC, merged