Implement coulomb + viscous model for friction compensation
robotology/icub-firmware pull request #350
Opened 2023-03-01 08:54 UTC by isorrentino

This PR implements a new friction model used for friction compensation in the case of the torque control mode active.

The mathematical expression of this law is
$\tau_F = coulomb * \text{sign} (\dot q) + viscous * \dot q$

The PR also replaces the source of the joint velocity in the friction compensation law. The one from the `2foc` is no longer used and is replaced by the one calculated by the Kalman filter.

cc @pattacini @sgiraz @DanielePucci @GiulioRomualdi

2023-03-02 15:47 UTC, marcoaccame requested changes
Hi @isorrentino the PR is fine.

What is missing however is the advancement of the application versions for the `ems`, `mc4plus` and `mc2plus` and the PR for the binaries. You can see this [one](https://github.com/robotology/icub-firmware-build/pull/66) for a reference.

You should build the binaries after you have rebased your `icub-firmware` vs `robotology/deve`l as there are other PRs in the process of being merged now and you have changed the versions of the applications and the build dates.

2023-03-08 16:44 UTC, isorrentino commented
Hi @marcoaccame, I should have completed what you asked. Hoping that everything is fine.

2023-03-08 22:09 UTC, sgiraz approved these changes
Everything seems ok from my side. Waiting for @marcoaccame review.

2023-03-09 14:34 UTC, marcoaccame approved these changes

2023-03-09 14:37 UTC, merged