Ergojoint support added (under #ifdef ERGOJOINT)
robotology/icub-firmware pull request #357
Opened 2023-03-09 08:58 UTC by ale-git

I've added support to torque measure in ergoCub new joint based on harmonic drive torsion.
To enable this feature ERGOJOINT macro must be defined in the project configuration.
The project built without ERGOJOINT macro is full compatible with standard EMS fw.

2023-03-09 16:47 UTC, maggia80 reviewed
@ale-git could you open a PR in icub-firmware-models where you define the original Simulink model from which you generated the code?

2023-03-10 09:46 UTC, marcoaccame requested changes
Hi, here are a few changes which may help:

- rebase vs latest `devel`  and solve conflicts. 
- create a PR of the used torque model inside https://github.com/robotology/icub-firmware-models and  make a reference to it inside this PR.
- move the model-based generated code under folder `emBODY\eBcode\arch-arm\mbd` as for instance done w/ the `kalman_filter`. 

Then, I assume that this PR will keep an experimental FW not yet to be deployed inside the robot. It will be in future, right? If so:

- revert the project `ems4rd.diagnostic2ready.uvprojx`so that is not affected (yet) by the new code. I see that it already compiles the new files.

- I suggest to shape the version number of the `ems4rd.ergojoint.uvprojx` using macro `ERGOJOINT`. That makes the experimental FW recognizable and at the same time it avoids conflicts in file `EOMtheEMSapplCfg_cfg.h`. Something like that:

  ```c++
  #if defined(WRIST_MK2)
      #define VERSION_MAJOR_OFFSET  20
  #elif defined(ERGOJOINT)
      #define VERSION_MAJOR_OFFSET 30
  #else
      #define VERSION_MAJOR_OFFSET 0
  #endif
  ```

2023-03-10 14:46 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/embobj/plus/board/EOappEncodersReader.c
> +                        #ifdef ERGOJOINT
One more thing: would it be possible to call the `MController_motor_calc_torque*()` functions inside the `MController`, for instance inside `MController_update_absEncoder_fbk()` which is the one that takes care of the encoder values? 

The benefit in this is that we keep the code more encapsulated. And also, we can have the torque computation for free also in the `amc` and future dual core boards which use a new simplified [encoder-reader](https://github.com/robotology/icub-firmware/blob/master/emBODY/eBcode/arch-arm/embot/app/eth/embot_app_eth_theEncoderReader.cpp).

2023-03-13 12:46 UTC, valegagge commented
> @ale-git could you open a PR in icub-firmware-models where you define the original Simulink model from which you generated the code?

It is in [ergocub-design-joint/blob/sim/ErgoJointTorqueControlGen.slx](https://github.com/icub-tech-iit/ergocub-design-joint/blob/sim/ErgoJointTorqueControlGen.slx)

2023-03-30 09:14 UTC, ale-git commented
We decided to suspend this PR, so I'm gong to put it in "on hold" state.

2024-02-12 10:15 UTC, marcoaccame commented
Hi @ale-git, I propose to close this PR as it is quite old and I believe it is maybe too difficult to rebase the fork vs latest devel. 
You can still re-open another one w/ similar content if you need.

2024-02-12 10:45 UTC, marcoaccame commented
> Hi @ale-git, I propose to close this PR as it is quite old and I believe it is maybe too difficult to rebase the fork vs latest devel. You can still re-open another one w/ similar content if you need.

OK. I will close then

2024-02-12 10:45 UTC, closed without merging