Finalization of calib type 14 on fingers.
robotology/icub-firmware pull request #363
Opened 2023-04-06 09:11 UTC by MSECode

Calibration type 14 tested on right arm of ergoCub.

Deleted calibration type 14 temp code from calibration type 6 methods.
Calibration type 14 firmware completed and tested on both bench setup and right arm.

2023-04-06 15:24 UTC, valegagge requested changes
Great work!!!

As we already discuss f2f, some small changes are needed.

Thank you

2023-04-06 15:24 UTC, valegagge commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/cfg/eoprot-callbacks/EoProtocolMC_fun_ems4rd.c
> +                       iCubCanProtCalibrator.params.type6.position = calibrator->params.type6.vmax;
Please remove changes not calibration 14 related.

2023-04-06 15:24 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +            // debug code
please comment the debug code.

2023-04-06 15:24 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +            snprintf(info, sizeof(info), "init traj: cpos=%.2f target=%.2f lim:%.2f %.2f", j_ptr->pos_fbk, j_ptr->running_calibration.data.type6.targetpos, j_ptr->pos_max, j_ptr->pos_min);
Good use of `sizeof`!!! :)

2023-04-06 15:24 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +                // change rotorLimit --> now only for debugging reasons
As we already said f2f, it's better to remove the inversion of the limits. 
The encoder resolution can have a sign.

2023-04-06 15:24 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Joint.c
> +static BOOL Joint_set_pos_ref_in_calib(Joint* o, CTRL_UNITS pos_ref, CTRL_UNITS vel_ref)
Fantastic! Conde factorization!!! Great!

2023-04-06 15:24 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/mc/JointSet.c
> +#ifndef WRIST_MK2
Attention! check carefully if `eomc_controlmode_cmd_direct` is before or after the `# ifndef WRIST_MK2`

2023-04-06 16:18 UTC, MSECode commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +            // debug code
done

2023-04-06 16:27 UTC, MSECode commented on emBODY/eBcode/arch-arm/embobj/plus/mc/JointSet.c
> +#ifndef WRIST_MK2
before `#ifndef`

2023-04-06 16:27 UTC, MSECode commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +                // change rotorLimit --> now only for debugging reasons
removed debug code. uncommented the reset of rotor limits couple of lines below.
Saving temporary rotor limits as fed by the user from the mechanical file in configuration xml file.
user should remember to check correct sign of the limits, i.e. min can be 0+something or 166*(gear_box=159) - something

2023-04-06 16:35 UTC, MSECode commented on emBODY/eBcode/arch-arm/embobj/plus/mc/JointSet.c
> +#ifndef WRIST_MK2
I'll align to devel

2023-04-06 17:27 UTC, marcoaccame commented
Hi, I will have a look first thing tomorrow morning.

2023-04-06 18:52 UTC, valegagge commented
We need to update the fw version and build date of all boards because the updated code is shared among them.

cc @MSECode

2023-04-06 19:42 UTC, MSECode commented
Yes 
I remember 
I've already tested the compilation on:
mc4plus
amcbldc
ems 

Are there other boards, which share the same code ?

Otherwise tomorrow I'lol generate the new hex for them and I'll add in the PR on firmware build the update of the xml file containing the latest board versions

2023-04-07 07:49 UTC, valegagge commented
> Are there other boards, which share the same code ?
> 

 mc2plus
thanks a lot!

cc @MSECode

2023-04-07 09:27 UTC, marcoaccame commented
> Yes I remember I've already tested the compilation on: mc4plus amcbldc ems
> 
> Are there other boards, which share the same code ?

They are: ems, mc4plus, m2plus, amc.

2023-04-07 09:43 UTC, marcoaccame requested changes
Hi, you need to address the following:

- Change the versions and date of the applications for `ems`, `mc4plus`, `mc2plus` and `amc`. Because: the `mc4plus` will effectively use calibration 14 on the robot, whereas the others have files in [here](https://github.com/robotology/icub-firmware-shared/pull/81/files) that are used for their compilation.
- wait for the OK for the following PR (but I can already say that it is OK)
   - https://github.com/robotology/icub-firmware-shared/pull/81 
- Produce a PR in icub-firmware-build for the above new binaries.
- Be sure that the tests on the robots are OK w/ the new binaries, using on the robot the xml files and the relevant icub-firmware-shared and icub-main
   - https://github.com/robotology/robots-configuration/pull/472 
   - https://github.com/robotology/icub-firmware-shared/pull/81
   - https://github.com/robotology/icub-main/pull/862

When everything is OK we can start merging `icub-firmware`, `icub-firmware-shared`, `icub-firmware-build`, `robots-configuration` and then when the CI is OK also `icub-main` (which depends from `icub-firmware-shared`).

2023-04-07 17:17 UTC, marcoaccame approved these changes

2023-04-07 17:19 UTC, marcoaccame commented
I have received green light from the tests on the robot, so I will merge everything

2023-04-07 17:22 UTC, merged