Calibration type 14 update fw
robotology/icub-firmware pull request #384
Opened 2023-06-05 13:01 UTC by MSECode

This PR contains the following updates:
- update versions for all `ETH` boards, since we have changed code that is shared for all of those boards.
- add extern method `eo_pos_Calibrate`  in `POS` for passing to the POS service calibration values for absolute encoder coming from the calibrator
- add static methods `s_eo_pos_joint_calibrate` and `s_eo_pos_sensor_config` for calibrate absolute sensor managed by POS service
- simply the calibration procedure in `Calibrators` class by reducing the steps and removing processes that are not necessary and/or meaningless
- add FAP absolute encoder directly to `JointSet` class, therefore encoder gets re-calibrated after POS service starts using data coming from calibrator configuration file

2023-06-06 07:17 UTC, MSECode commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/EOthePOS_hid.h
> +    eObool_t                                calibrated;
I use it here:
![image](https://github.com/robotology/icub-firmware/assets/77933235/70cd1ef6-bddf-4ba2-9dd5-edf5f95851b2)

in order to distinguish the overriding of the calibration parameters from the configuration of the POS service

2023-06-06 11:05 UTC, marcoaccame requested changes

2023-06-06 11:07 UTC, marcoaccame commented
Apart from the small thing above all is great. Well done.

P.S. I assume that everything was tested on the robot and ready to go.

2023-06-07 07:37 UTC, MSECode commented
> Apart from the small thing above all is great. Well done.
> 
> P.S. I assume that everything was tested on the robot and ready to go.

Kinda yes,
I'm waiting for the review from @valegagge and then we are ready to merge.
The code has been tested deeply on the left arm bench setup but not yet on the robot since it was not available due to ICRA.
As soon as it is back I'll test the code on it.

2023-06-09 12:01 UTC, valegagge approved these changes

2023-06-09 13:11 UTC, valegagge commented
Tested on the robot by @MSECode. All is fine.

2023-06-12 06:29 UTC, marcoaccame approved these changes
ok, thanks. I see that the `EOthePOS` has the suggested changes.

2023-06-12 06:29 UTC, merged