AMDBLDC: add thermal model running at 10ms and reusable functions from codegen ( icub-fw-models: 2e2670b)
robotology/icub-firmware pull request #391
Opened 2023-06-27 10:19 UTC by mfussi66

This PR aligns the AMCBLDC code to the [latest mbd  code generation](https://github.com/robotology/icub-firmware-models/commit/2e2670b37640340f0e34f3cd745920b43e2ff54c), with the following features:
- A linear thermal model is added, running at 10ms, to estimate the temperature: this is a first stepping stone for the i2t protection, no supervisor infrastructure is added yet
- Adapted architectural model to allow reusable functions

cc @pattacini

2023-06-28 11:23 UTC, pattacini commented on emBODY/eBcode/arch-arm/board/amcbldc/application/src/app-board-amcbldc/embot_app_board_amcbldc_theMBD.cpp
We have now 2 timer functions: one at 1 ms and one at 10 ms 👍🏻

2023-06-28 11:23 UTC, pattacini approved these changes

2023-06-28 11:57 UTC, pattacini reviewed
Hi @marcoaccame 

Please, also review the STRAIN2c patch.

2023-06-28 11:57 UTC, pattacini commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/EOtheCANdiscovery2.c
> +        case eobrd_cantype_strain2c:
cc @marcoaccame

2023-06-28 11:57 UTC, pattacini commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/cfg/eoemsappl/EOMtheEMSapplCfg_cfg.h
> +#define EOMTHEEMSAPPLCFG_VERSION_MINOR          69
cc @marcoaccame

2023-07-03 08:12 UTC, marcoaccame requested changes
The `strain2c` patch is OK as long as you update the application versions of the ETH boards.

Some minor changes are needed. To group them all in here:

- [x] update application version of the `ems`, `mc4plus`, `mc2plus`;
- [ ] propagate changes of MBD also for the `amc2c` board in function `embot::app::board::amc2c::theMBD::Impl::tick()`;
- [ ] increase application version of `amcbldc`.

The application version of the `amcbldc` is inside file `embot_app_board_amcbldc_info.cpp`:

```C++
namespace embot::app::board::amcbldc::info {
    
    constexpr embot::prot::can::applicationInfo applInfo 
    {   
        embot::prot::can::versionOfAPPLICATION {2, 0, 2},    
        embot::prot::can::versionOfCANPROTOCOL {2, 0}   
    };
```

2023-07-03 08:12 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/board/amcbldc/application/src/app-board-amcbldc/embot_app_board_amcbldc_theMBD.cpp
OK. We probably need to propagate this change to the MBD engine of the `amc2c` code (the CM4 core of the `amc`) in file `embot_app_board_amc2c_theMBD.cpp`, function `embot::app::board::amc2c::theMBD::Impl::tick()`.

Because both `amcbldc` and `amc2c` share the same model-based-design code, but for now the have a dedicated MBD engine.

2023-07-03 10:43 UTC, mfussi66 commented
>   propagate changes of MBD also for the `amc2c` board in function `embot::app::board::amc2c::theMBD::Impl::tick()`;

@marcoaccame FYI this change requires also the change of the keil project, by adding the thermal model sources

2023-07-03 11:01 UTC, mfussi66 commented
@marcoaccame 

>     * [ ]  update application version of the `ems`, `mc4plus`, `mc2plus`;

Done in [`10d1418` (#391)](https://github.com/robotology/icub-firmware/pull/391/commits/10d14182bf04802e92ae34fe5ecc6fcc8b1f5367)

>     * [ ]  propagate changes of MBD also for the `amc2c` board in function `embot::app::board::amc2c::theMBD::Impl::tick()`;

Done in [`d938748` (#391)](https://github.com/robotology/icub-firmware/pull/391/commits/d938748c48eae74969b4c1286d63c0290c68b581)

>     * [ ]  increase application version of `amcbldc`.

Done in [`8332b36` (#391)](https://github.com/robotology/icub-firmware/pull/391/commits/8332b3683c92cab0b5fec6cd0063fe4f63ee6bcb)

2023-07-04 07:11 UTC, marcoaccame approved these changes
That's OK, @mfussi66. Thanks.

2023-07-04 07:11 UTC, merged