Fix/battery charge
robotology/icub-firmware pull request #395
Opened 2023-07-11 10:30 UTC by MSECode

This PR brings the following fixes to the BAT code:
- fix the battery voltage send to the specific port to be shown in deciVolt
- align the message send from BAT to EMS board to be aligned with the BMS protocol info

2023-07-11 12:43 UTC, MrAndrea approved these changes
Ok

2023-07-12 10:03 UTC, valegagge commented on emBODY/eBcode/arch-arm/board/bat/BAT_Rev_B/Inc/BAT_B.h
I guess the variable `vBatterydv` is used in the `main.c` file only. So the best practice is to define a local variable and not a global one.
So the `vBatterydv' could be defined in the` main.c` file inside the `case 0x5`.

This in only a suggestion, not a change request. :)

2023-07-12 10:08 UTC, valegagge requested changes
all is OK. 
For the sake of accuracy, please remove the changes in `embot_app_eth_theBATservice.cpp`

2023-07-12 10:08 UTC, valegagge commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/embot_app_eth_theBATservice.cpp
Please remove these changes from the PR because they are meaningless and not related to your improvement.

2023-07-12 14:48 UTC, MSECode commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/embot_app_eth_theBATservice.cpp
I'll fix that

2023-07-12 15:51 UTC, valegagge approved these changes
LGTM

2023-07-12 15:52 UTC, merged