Update fw to v1.3.1 and display variable:
robotology/icub-firmware pull request #421
Opened 2023-09-29 13:07 UTC by MSECode

add HSM hw/fw faults flag to status_B
move sending of CAN frames from 1ms to 100ms timer if fault before next 100ms trigger sending of CAN frames in that moment if fault happens save and send to display that currents and voltages Update battery fw for sending status to display, plus triggering fault screens correctly

2023-10-03 12:33 UTC, valegagge requested changes
All is ok, since the results of the test! well done.

I suggested you a very small request for code cleaning.

2023-10-03 12:33 UTC, valegagge commented on emBODY/eBcode/arch-arm/board/bat/BAT_Rev_B/Inc/BAT_B.h
> +// TEST VARIABLES
Hi @MSECode,
I'm not mistaken, These variables had been used only for test purpose.
So, it would be better remove them or comment if you'll use again for other testing on banching.

2023-10-03 12:34 UTC, MSECode commented on emBODY/eBcode/arch-arm/board/bat/BAT_Rev_B/Inc/BAT_B.h
> +// TEST VARIABLES
thanks for the check. Good to remove it.

2023-10-03 12:48 UTC, MSECode commented
removed test variables 4ce53fcb1fc7128d3bf948889052598be7e3f20a

2023-10-04 06:54 UTC, valegagge approved these changes
Good work!!!

2023-10-04 06:55 UTC, merged