Now the joints can run based only to motor encoder - without AMO sensors - and calibrate in hard stop.
robotology/icub-firmware pull request #438
Opened 2023-11-07 15:01 UTC by ale-git

At present, robots like iCub 3 and ErgoCub can use AMO sensors in incremental mode with hard stop calibration.
This new version allows the same robots to run without AMO sensors at all, only relying on motor encoders.

PLEASE DON'T MERG YET, TO BE TESTED ONCE MORE.

2023-11-08 08:42 UTC, valegagge commented
Hi @ale-git,
please add a description of your changes and how they impact on the workflow of the embedded motor control. thank you!

2023-11-10 13:54 UTC, valegagge commented
https://github.com/robotology/icub-firmware/assets/4233231/8fe95e30-80e2-4bdf-bbe7-33a3fba7503d

2023-11-10 15:46 UTC, ale-git commented
In the motion control library there was still a missing step to be able to control a joint with only motor encoder, hard stop calibrated, with a EMS+2FOC architecture: before starting the hard stop calibration procedure the EMS must wait that the 2FOC itself is calibrated (rotor encoder idex found), otherwise we'll have a hard stop false detection caused by the fact that the 2FOC controlled motor doesn't move until the 2FOC is internally calibrated. In fact, the hard stop detection is base on a timeout euristics: the EMS commands a calibration PWM to the 2FOC, and if the joint doesn't move for a certain time it is assumed that the hard stop is reached. For the reason above, it was already working on MC4+ boards but not on EMS+2FOC boards. Now this PR fixes this gap, providing the right synchronization between EMS and 2FOC during hard stop calibration.

2023-11-13 07:37 UTC, valegagge requested changes
Hi @ale-git ,
I reported in the review comments some small changes that I think they are necessary.

After the changes, a the fw should be tested again.

2023-11-13 07:37 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/mc/JointSet.c
> +                o->hard_stop_calib.space_thr = 120;
I assume you would have liked to use the `time_thr`here or in the next line.

2023-11-13 07:37 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/mc/JointSet.c
> +                o->hard_stop_calib.space_thr = 12000;
same comment as the previous one

2023-11-13 07:37 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/mc/CalibrationHelperData.h
> +    int32_t space_thr;
Which is the measure unit? Maybe you can add a comment here nad for the field `time_thr`

2023-11-13 07:37 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +            if (Motor_is_still(o->motor+m, 12000, 1000))
Why here you don't use the hard_stop_calib info configured in the `JointSet_calibrate`function?

I guess the use of hardcoded values here and some lines below hides the `time_thr`configuration in the `JointSet_calibration.

2023-11-13 07:42 UTC, valegagge commented
Hi @ale-git ,
regarding the version number of `amc` fw you could find it [here](https://github.com/robotology/icub-firmware/pull/431/files#diff-d1e0d10a445c3e750355e3bc8cfc92542ff7292538bc5b569c897ced44fbee8d).

2023-11-13 09:05 UTC, ale-git commented on emBODY/eBcode/arch-arm/embobj/plus/mc/JointSet.c
> +                o->hard_stop_calib.space_thr = 120;
Thanks for spotting it but, as you've seen later, they are just placeholders in case that these parameters will be added to the protocol. Anyway, I don't think that they need to be made configurable since they are pretty universal and don't need to be fine tuned.

2023-11-13 09:06 UTC, ale-git commented on emBODY/eBcode/arch-arm/embobj/plus/mc/CalibrationHelperData.h
> +    int32_t space_thr;
ok

2023-11-13 09:10 UTC, ale-git commented on emBODY/eBcode/arch-arm/embobj/plus/mc/Calibrators.c
> +            if (Motor_is_still(o->motor+m, 12000, 1000))
As I said above, the parameters are just placeholders if we want make these values configurable. I'll add a comment in the code when they are defined and assigned.

2023-11-13 09:26 UTC, ale-git commented
Since the modifications consists in comments and two not used variables I'm going to rebuild the .hex (the amc has still to be done anyway), but there is no need to test it again. Generally speaking,   I suggest that our workflow should be corrected: if you want to review the PRs line by line it is well appreciated, but it should be done **before** the firmware is tested working properly, not after. Testing is a very time consuming activity, and modifications to a already tested and working version makes the previous test a useless waste of time.

2023-11-13 10:25 UTC, valegagge commented
as discussed f2f with @ale-git, we decided that in the `jointSet_calibrate` we'll initialize correctly the `hard_stop_calib` values and in the `JointSet_do_wait_calibration_10` we'll use that structure in order to avoid to leave raw values around the code. This small change should improve the maintainability and comprehension of the code.

If in the future we want to make those thresholds parametrized, we just need to set the new parameter in the `hard_stop_calib` structure in `jointSet_calibrate`.

We also agreed, that more tests are no longer necessary.

2023-11-13 10:26 UTC, valegagge commented
> Since the modifications consist in comments and two not used variables I'm going to rebuild the .hex (the amc has still to be done anyway), but there is no need to test it again. Generally speaking, I suggest that our workflow should be corrected: if you want to review the PRs line by line it is well appreciated, but it should be done **before** the firmware is tested working properly, not after. Testing is a very time consuming activity, and modifications to a already tested and working version makes the previous test a useless waste of time.

Yes, I agree with you. we need to plan testing activities better.

2023-11-13 12:27 UTC, ale-git commented
I pushed all the required changes.

2023-11-13 13:27 UTC, valegagge approved these changes
LGTM 🚀

2023-11-13 17:22 UTC, marcoaccame approved these changes
OK @ale-git, thanks

2023-11-13 17:27 UTC, merged