Feature/fw updater bat
robotology/icub-firmware pull request #447
Opened 2023-12-12 17:37 UTC by MSECode

2024-01-08 11:59 UTC, valegagge requested changes
I added a comment. What do you think?

2024-01-08 11:59 UTC, valegagge commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/embot_app_eth_theBATservice.cpp
> +  if(service.servconfig.data.as.battery.canmonitorconfig.periodofcheck == 0)
Hi @MSECode,
I guess that here an `else` is missing. That is, if the `periodofcheck` in the configuration sent by YRI is zero, then we need to use the default configuration, also for the other parameters. 

Moreover, the default parameters in the line 93 should be value 250 instead of 200 as you mentioned in a comment in the issue.

2024-01-08 16:33 UTC, MSECode commented on emBODY/eBcode/arch-arm/board/ems004/appl/v2/src/eoappservices/embot_app_eth_theBATservice.cpp
> +  if(service.servconfig.data.as.battery.canmonitorconfig.periodofcheck == 0)
done

2024-01-09 14:37 UTC, MSECode commented
This PR is linked to:
- [icub-firmware-shared](https://github.com/robotology/icub-firmware-shared/pull/91)
- [icub-firmware-build](https://github.com/robotology/icub-firmware-build/pull/126)

2024-01-09 20:41 UTC, valegagge approved these changes
Well done! 🚀 

The EMS works properly only if the pr https://github.com/robotology/robots-configuration/pull/603 has been merged, because the battery needs the CAN address 2 as it is explained in the note `Just a more note about the need to set the address 2 to the bat board` in this [comment](https://github.com/robotology/icub-firmware/issues/445#issuecomment-1870195848)

2024-01-10 09:25 UTC, marcoaccame approved these changes
it is ok, thanks

2024-01-10 09:25 UTC, merged