AMC-BLDC - test FW
robotology/icub-firmware pull request #453
Opened 2023-12-20 16:20 UTC by davidetome

This PR adds test `FW` (on-board tests) which will be used in `IPTS` for board testing

cc @Nicogene @pattacini @marcoaccame

2024-01-08 08:47 UTC, marcoaccame requested changes
Hi @davidetome, the PR is fine. Only thing, pls fix comments on measuremnt units of temperature

2024-01-08 08:47 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/board/amcbldc/bsp/embot_hw_bsp_amcbldc.h
> +    float getCIN();
maybe add also `float getTEMP()` and specify measurement units, maybe celsius degrees?

2024-01-08 08:47 UTC, marcoaccame commented on emBODY/eBcode/arch-arm/board/amcbldc/test/src/motorhal2/analog.c
> + * @return  temp voltage in mV [0 .. 57000mV]
pls fix measurement units

2024-01-08 14:25 UTC, davidetome commented
ciao @marcoaccame thaks! I did the mods...

2024-01-08 14:25 UTC, davidetome commented on emBODY/eBcode/arch-arm/board/amcbldc/bsp/embot_hw_bsp_amcbldc.h
> +    float getCIN();
done!

2024-01-08 14:26 UTC, davidetome commented on emBODY/eBcode/arch-arm/board/amcbldc/test/src/motorhal2/analog.c
> + * @return  temp voltage in mV [0 .. 57000mV]
done!

2024-01-11 07:57 UTC, marcoaccame approved these changes
OK, thanks

2024-01-11 07:57 UTC, merged