Fix AksIM2 diagnostic display
robotology/icub-firmware pull request #549
Opened 2024-12-18 09:43 UTC by AntonioViscomi

Hello everyone,
With this PR I would like to merge a modified version of  `EOappEncodersReader.c`, specifically in the lines reported [here](https://github.com/robotology/icub-firmware/blob/devel/emBODY/eBcode/arch-arm/embobj/plus/board/EOappEncodersReader.c#L722-L766).
This modification is done to avoid sending multiple error messages (invalid data, invalid crc, close to limits warning) when the encoder is retrieved as `disconnected`.

2024-12-20 21:27 UTC, valegagge requested changes

2024-12-20 21:27 UTC, valegagge commented on emBODY/eBcode/arch-arm/embobj/plus/board/EOappEncodersReader.c
> +                        rawValue = (rawValue >> 1) & 0x3FFF;
Hi @AntonioViscomi ,
why there are these changes? Maybe you are not rebased on the top of devel

2024-12-21 14:42 UTC, AntonioViscomi commented on emBODY/eBcode/arch-arm/embobj/plus/board/EOappEncodersReader.c
> +                        rawValue = (rawValue >> 1) & 0x3FFF;
Hi @valegagge 
You are definitely right, I forgot to rebase.
The PR should be fine now, thanks for your suggestion.

2024-12-30 10:00 UTC, valegagge commented
Just a note: this PR contains a very small change that affects only the diagnostic of Aksim, so it is not necessary to create the relative icub-fw-build PR with the new exe for all boards.

2024-12-30 10:00 UTC, merged